//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelUsers
    {
        public int PermissionId { get; set; }
        public string UserId { get; set; }
        public int HotelId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Hotels Hotels { get; set; }
        public virtual HotelPermissions HotelPermissions { get; set; }
    }
}
