//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureResolutions
    {
        public int Id { get; set; }
        public System.Guid PictureId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Size { get; set; }
        public string FileName { get; set; }
        public int FileUrlId { get; set; }
    
        public virtual Pictures Pictures { get; set; }
        public virtual PictureUrls PictureUrls { get; set; }
    }
}
