//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationTransaction()
        {
            this.TransactionsForReservations = new HashSet<TransactionsForReservations>();
        }
    
        public System.Guid Id { get; set; }
        public string UserTransactionIsForId { get; set; }
        public string UserTransactionCompletedById { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateCompleted { get; set; }
        public int TransactionType { get; set; }
        public int TransactionPaymentDetailsId { get; set; }
        public decimal AmountCharged { get; set; }
        public int TransactionStatusId { get; set; }
    
        public virtual AspNetUsers UserCreatedBy { get; set; }
        public virtual AspNetUsers UserFor { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsForReservations> TransactionsForReservations { get; set; }
        public virtual TransactionPaymentDetails TransactionPaymentDetails { get; set; }
        public virtual TransactionStatus TransactionStatus { get; set; }
    }
}
