//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReserveItems
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public int ReservationId { get; set; }
        public decimal PricePreTax { get; set; }
        public decimal TaxRate { get; set; }
        public bool IgnoreQuantityRestrictions { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime DateReservedFor { get; set; }
        public decimal FinalPrice { get; set; }
    
        public virtual VenueItems VenueItems { get; set; }
        public virtual ReservationGroup ReservationGroup { get; set; }
    }
}
