//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePermissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SitePermissions()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Hotel { get; set; }
        public int Price { get; set; }
        public int OtherReservations { get; set; }
        public int Icon { get; set; }
        public int PersonalReservation { get; set; }
        public int Users { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual Permissions HotelPermissions { get; set; }
        public virtual Permissions IconPermissions { get; set; }
        public virtual Permissions OtherReservationsPermissions { get; set; }
        public virtual Permissions PersonalReservationsPermissions { get; set; }
        public virtual Permissions PricePermissions { get; set; }
        public virtual Permissions OtherUsersPermissions { get; set; }
    }
}
