//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsAndConditions
    {
        public int Id { get; set; }
        public System.DateTime DateEffective { get; set; }
        public int MiscellaneousId { get; set; }
    
        public virtual MiscellaneousHtmlTable MiscellaneousHtmlTable { get; set; }
    }
}
