//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolReservation.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueItemQuantity
    {
        public int ItemId { get; set; }
        public System.DateTime DateEffective { get; set; }
        public int Quantity { get; set; }
        public int Id { get; set; }
    
        public virtual VenueItems VenueItems { get; set; }
    }
}
